# make_golden.py — build an evaluation golden set from the chunks table.
#
# One question per chunk, generated by Claude, each carrying a VERBATIM substring of the
# chunk that contains the answer. That substring is what makes the set verifiable: a
# retrieved chunk counts as relevant iff it contains it, so relevance never depends on
# chunk ids that re-ingest reassigns.
import argparse
import asyncio
import json
import re
import sys

import psycopg

from config import Settings
from db import DSN
from llm import cost_usd, get_client

MODEL = "claude-opus-5"
CONCURRENCY = 8

SYSTEM = """You generate evaluation questions for a Kubernetes docs search system.
Given a documentation chunk, write ONE natural question a user would ask that THIS chunk answers,
plus a short verbatim substring (5-10 words) from the chunk that contains the answer.
Return ONLY JSON: {"question": "...", "answer_substring": "..."}
Skip chunks that are pure markup, navigation, or have no real content — return {"skip": true}."""

# The schema enforces the shape the prompt describes, so no output is ever unparseable.
# `skip` is the discriminator; the two text fields are null on a skip.
_NULLABLE_STR = {"anyOf": [{"type": "string"}, {"type": "null"}]}
SCHEMA = {
  "type": "object",
  "properties": {
    "skip": {"type": "boolean"},
    "question": _NULLABLE_STR,
    "answer_substring": _NULLABLE_STR,
  },
  "required": ["skip", "question", "answer_substring"],
  "additionalProperties": False,
}


def _norm(s: str) -> str:
  # Collapse whitespace on both sides before matching: the model reflows newlines inside
  # the substring it quotes, which would otherwise fail a naive `in` check.
  return re.sub(r"\s+", " ", s).strip().lower()


def load_chunks(source: str, limit: int | None) -> list[dict]:
  conn = psycopg.connect(DSN, autocommit=True)
  sql = "SELECT id, doc_id, section, content FROM chunks WHERE source = %s ORDER BY chunk_index"
  params: list = [source]
  if limit:
    sql += " LIMIT %s"
    params.append(limit)
  rows = conn.execute(sql, params).fetchall()
  return [{"id": i, "doc_id": d, "section": s, "content": c} for (i, d, s, c) in rows]


async def _one(client, settings: Settings, chunk: dict, sem: asyncio.Semaphore) -> dict:
  async with sem:
    try:
      resp = await client.messages.create(
        model=MODEL,
        max_tokens=2000,                     # room for thinking + the small JSON payload
        system=SYSTEM,
        output_config={
          "effort": "low",                   # mechanical extraction — no need to reason hard
          "format": {"type": "json_schema", "schema": SCHEMA},
        },
        messages=[{"role": "user", "content": chunk["content"]}],
      )
    except Exception as e:
      # Never let one failure discard the whole run: a rate limit or a spend cap hit
      # mid-corpus should still leave every question generated before it on disk.
      return {"status": "error", "usage": (0, 0), "chunk": chunk, "error": repr(e)[:200]}

  usage = (resp.usage.input_tokens, resp.usage.output_tokens)
  if resp.stop_reason == "refusal":
    return {"status": "refused", "usage": usage, "chunk": chunk}

  text = next((b.text for b in resp.content if b.type == "text"), None)
  if text is None:                           # e.g. truncated before any text block
    return {"status": "empty", "usage": usage, "chunk": chunk}

  out = json.loads(text)                     # output_config.format guarantees valid JSON
  if out is None:
    return {"status": "empty", "usage": usage, "chunk": chunk}
  if out["skip"] or not out["question"] or not out["answer_substring"]:
    return {"status": "skipped", "usage": usage, "chunk": chunk}

  # The load-bearing check: the quoted answer must really be in the chunk. A question whose
  # substring was paraphrased is unverifiable, so it does not belong in a golden set.
  if _norm(out["answer_substring"]) not in _norm(chunk["content"]):
    return {"status": "not_verbatim", "usage": usage, "chunk": chunk, "raw": out}

  return {"status": "ok", "usage": usage, "chunk": chunk, "out": out}


async def main() -> None:
  ap = argparse.ArgumentParser()
  ap.add_argument("--source", default="k8s")
  ap.add_argument("--limit", type=int, default=None, help="pilot on the first N chunks")
  ap.add_argument("--out", default="golden_set.json")
  ap.add_argument("--resume", action="store_true",
                  help="keep items already in --out and only generate the missing chunks")
  args = ap.parse_args()

  chunks = load_chunks(args.source, args.limit)
  if not chunks:
    sys.exit(f"no chunks for source={args.source!r}")

  # Resume: keep whatever a previous (possibly interrupted) run produced and only ask for
  # the chunks still missing. Generation is the expensive part — never redo it.
  existing: list[dict] = []
  if args.resume:
    try:
      existing = json.load(open(args.out, encoding="utf-8"))["items"]
    except (FileNotFoundError, KeyError, json.JSONDecodeError):
      existing = []
    done = {it["chunk_id"] for it in existing}
    chunks = [c for c in chunks if c["id"] not in done]
    print(f"resuming: {len(existing)} already done, {len(chunks)} to go")

  if not chunks:
    sys.exit("nothing left to generate")
  print(f"generating over {len(chunks)} chunks (source={args.source!r}, model={MODEL})")

  settings = Settings()
  client = get_client(settings.anthropic_api_key)
  sem = asyncio.Semaphore(CONCURRENCY)
  results = await asyncio.gather(*(_one(client, settings, c, sem) for c in chunks))

  in_tok = sum(r["usage"][0] for r in results)
  out_tok = sum(r["usage"][1] for r in results)
  counts: dict[str, int] = {}
  for r in results:
    counts[r["status"]] = counts.get(r["status"], 0) + 1

  fresh = [
    {
      "question": r["out"]["question"],
      "answer_substring": r["out"]["answer_substring"],
      "chunk_id": r["chunk"]["id"],          # valid for THIS ingest; substring is the durable key
      "doc_id": r["chunk"]["doc_id"],
      "section": r["chunk"]["section"],
    }
    for r in results if r["status"] == "ok"
  ]
  golden = existing + fresh
  with open(args.out, "w", encoding="utf-8") as f:
    json.dump({"source": args.source, "model": MODEL, "items": golden}, f,
              ensure_ascii=False, indent=2)

  print(f"\nkept {len(fresh)} / {len(chunks)}   " +
        "  ".join(f"{k}={v}" for k, v in sorted(counts.items())))
  print(f"tokens in={in_tok} out={out_tok}  cost=${cost_usd(MODEL, in_tok, out_tok):.2f}")
  print(f"wrote {args.out}  ({len(golden)} items total)")

  errs = [r for r in results if r["status"] == "error"]
  if errs:
    print(f"\n{len(errs)} chunk(s) failed — first error: {errs[0]['error']}")
    print(f"re-run with --resume to fill the gaps without regenerating what's done")


if __name__ == "__main__":
  asyncio.run(main())
